name: particle_image
version: 0.0.1
# TODO

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/default.png
