name: particle_image
description: "The Particle Image is a high performance particle effects flutter widget."
version: 0.0.2+1
repository: https://github.com/thize/Flutter-Particle-Image
issue_tracker: https://github.com/thize/Flutter-Particle-Image/issues
documentation: https://github.com/thize/Flutter-Particle-Image

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/default.png

topics:
  - particle
  - particles
  - visualization
  - game
  - effects
